# Generated by Django 6.0.3 on 2026-03-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_person_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='paye',
            field=models.CharField(blank=True, choices=[('Global', 'Global'), ('Money', 'Money')], max_length=10),
        ),
    ]
