# Generated by Django 6.0.3 on 2026-03-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_person_paye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='paye',
        ),
    ]
